/**
 * AgentEngine - Native LLM Orchestrator
 * Bridging LLM thinking capabilities directly with Cerebria OS Kernel
 */

import { LLMProvider, ChatMessage, LLMConfig } from './LLMProvider';
import EventBus from '../core/EventBus';

export interface AgentEngineOptions extends LLMConfig {
  /** Maximum reasoning iterations before the loop is aborted. Default: 10 */
  maxIterations?: number;
}

export class AgentEngine {
  private llm: LLMProvider;
  private system: any; // Context to Cerebria system instance
  private maxIterations: number;

  constructor(system: any, config: AgentEngineOptions) {
    this.system = system;
    this.llm = new LLMProvider(config);
    this.maxIterations = config.maxIterations ?? 10;
  }

  /**
   * Execute an autonomous reasoning loop based on a prompt
   */
  async run(prompt: string, systemPrompt?: string): Promise<string> {
    const messages: ChatMessage[] = [];
    if (systemPrompt) {
      messages.push({ role: 'system', content: systemPrompt });
    }
    messages.push({ role: 'user', content: prompt });

    // Extract tool definitions natively from the kernel's sandboxed MCP registry
    const availableTools = this.system.mcpRegistry ? this.system.mcpRegistry.getToolsSchema() : [];

    let synthesisComplete = false;
    let finalResponse = '';
    let iterations = 0;

    while (!synthesisComplete) {
      if (iterations >= this.maxIterations) {
        throw new Error(
          `[AgentEngine] Reasoning loop exceeded maxIterations (${this.maxIterations}). ` +
          'The LLM may be stuck in a tool-call cycle.'
        );
      }
      iterations++;

      console.log(`[AgentEngine] 🧠 Thinking... (${messages.length} msgs in context)`);
      EventBus.getInstance().emit('agent:thought', { action: 'thinking', messageCount: messages.length });
      const response = await this.llm.invoke(messages, availableTools);
      messages.push(response);

      // Check for OS Tool Execution Intent
      if (response.tool_calls && response.tool_calls.length > 0) {
        for (const toolCall of response.tool_calls) {
          const functionName = toolCall.function.name;
          const args = toolCall.function.arguments ? JSON.parse(toolCall.function.arguments) : {};
          
          console.log(`[AgentEngine] ⚙️ Dispatching Kernel Action: ${functionName}`, args);
          EventBus.getInstance().emit('agent:tool_call', { tool: functionName, args });
          
          // Delegate the actual tool execution to the OS Worker Pool
          // By converting this into a Task Manager job, we get native timeout, retry, and durability specs.
          const taskId = await this.system.taskManager.createTask(
            `Agent Intent: ${functionName}`,
            'Executing tool call generated by LLM reasoning context',
            {
              priority: 'high',
              intent: { action: 'mcp:execute', tool: functionName, args }
            }
          );
          
          let result;
          try {
            result = await this.waitForTaskCompletion(taskId);
          } catch (e: any) {
            result = { isError: true, content: [{ type: 'text', text: e.message }] };
          }
          
          messages.push({
            role: 'tool',
            content: typeof result === 'string' ? result : JSON.stringify(result),
            tool_call_id: toolCall.id,
            name: functionName
          });
        }
      } else {
        // Final text payload reached
        console.log('[AgentEngine] ✅ Final Synthesis Achieved.');
        EventBus.getInstance().emit('agent:thought', { action: 'synthesis', content: response.content });
        synthesisComplete = true;
        finalResponse = response.content || '';
      }
    }
    return finalResponse;
  }

  /**
   * Utility to wait for the persistent OS execution thread to finish.
   * Cleans up event listeners in all exit paths (resolve, reject, timeout).
   */
  private waitForTaskCompletion(taskId: string): Promise<any> {
    return new Promise((resolve, reject) => {
      const onResume = (data: any) => {
        if (data.taskId === taskId) {
          cleanup();
          resolve(data.result);
        }
      };
      
      const onFailed = (data: any) => {
        if (data.taskId === taskId) {
          cleanup();
          reject(new Error(data.error));
        }
      };

      const cleanup = () => {
        EventBus.getInstance().off('task:resumed', onResume);
        EventBus.getInstance().off('task:failed', onFailed);
        clearTimeout(timeoutHandle);
      };

      EventBus.getInstance().on('task:resumed', onResume);
      EventBus.getInstance().on('task:failed', onFailed);
      
      // We set the ceiling timeout slightly above WorkerPool's inner bounds
      const timeoutHandle = setTimeout(() => {
        cleanup();
        reject(new Error(`Kernel Task [${taskId}] timed out. Executor failed to return.`));
      }, 65000);
    });
  }
}
